/* GENERATED by scripts/aos/export_console.py — do not edit. */
export const KERNEL = {
 "generated": "2026-07-25T16:16:23Z",
 "goal": {
  "id": "GOAL-001",
  "name": "talabat 2026 $175m capital-allocation Business Plan",
  "charter": "Problem_Charter.md"
 },
 "workflow": [
  {
   "id": "goal",
   "name": "Goal",
   "status": "done",
   "detail": "Problem Charter active — $175m allocation (pivoted 2026-07-23)"
  },
  {
   "id": "planning",
   "name": "Planning",
   "status": "done",
   "detail": "Part A setup 12/12"
  },
  {
   "id": "execution",
   "name": "Execution",
   "status": "done",
   "detail": "14/14 sections independently verified"
  },
  {
   "id": "validation",
   "name": "Validation",
   "status": "active",
   "detail": "Whole-plan gates 0/6"
  },
  {
   "id": "review",
   "name": "Review",
   "status": "todo",
   "detail": "Executive read-through after gates"
  },
  {
   "id": "approval",
   "name": "Approval",
   "status": "active",
   "detail": "Open: role mapping (6 members ↔ 5 roles); all 14 DEC records approved"
  },
  {
   "id": "publish",
   "name": "Publish",
   "status": "todo",
   "detail": "DOCX/PDF + OS doc + 30-slide deck → Outputs/"
  }
 ],
 "sections": [
  {
   "n": 1,
   "name": "Executive Summary (SCQA)",
   "status": "done_iv"
  },
  {
   "n": 2,
   "name": "Business Description",
   "status": "done_iv"
  },
  {
   "n": 3,
   "name": "Market Analysis",
   "status": "done_iv"
  },
  {
   "n": 4,
   "name": "Value Proposition",
   "status": "done_iv"
  },
  {
   "n": 5,
   "name": "AI Technology and Development",
   "status": "done_iv"
  },
  {
   "n": 6,
   "name": "Business Model and Revenue Streams",
   "status": "done_iv"
  },
  {
   "n": 7,
   "name": "Marketing and Sales Strategy",
   "status": "done_iv"
  },
  {
   "n": 8,
   "name": "Operations Plan",
   "status": "done_iv"
  },
  {
   "n": 9,
   "name": "Financial Plan",
   "status": "done_iv"
  },
  {
   "n": 10,
   "name": "Risk Analysis",
   "status": "done_iv"
  },
  {
   "n": 11,
   "name": "CSR & Responsible AI",
   "status": "done_iv"
  },
  {
   "n": 12,
   "name": "Implementation Plan",
   "status": "done_iv"
  },
  {
   "n": 13,
   "name": "Monitoring and Evaluation (KPIs)",
   "status": "done_iv"
  },
  {
   "n": 14,
   "name": "Appendices + traceability note",
   "status": "done_iv"
  }
 ],
 "plan": [
  {
   "stage": "14",
   "action": "Whole-plan stage 14 — Cross-section consistency review",
   "owner": "`qa-review-agent`"
  }
 ],
 "waveBudget": 4,
 "validation": {
  "1": {
   "citation": {
    "verdict": "PASS",
    "stage": "pass2-main"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "pass2-main"
   }
  },
  "2": {
   "citation": {
    "verdict": "PASS",
    "stage": "pass2"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "reverify"
   }
  },
  "3": {
   "citation": {
    "verdict": "PASS",
    "stage": "reverify"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "reverify"
   }
  },
  "4": {
   "citation": {
    "verdict": "PASS",
    "stage": "reverify"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "reverify"
   }
  },
  "5": {
   "citation": {
    "verdict": "PASS",
    "stage": "reverify"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "reverify"
   }
  },
  "6": {
   "citation": {
    "verdict": "PASS",
    "stage": "reverify"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "reverify"
   }
  },
  "7": {
   "citation": {
    "verdict": "PASS",
    "stage": "reverify"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "reverify"
   }
  },
  "8": {
   "citation": {
    "verdict": "FAIL",
    "stage": "pass3-main",
    "chain": "closed-by-fix-record"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "pass2-main"
   }
  },
  "9": {
   "citation": {
    "verdict": "PASS",
    "stage": "pass3-main"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "pass2-main"
   }
  },
  "10": {
   "citation": {
    "verdict": "PASS",
    "stage": "pass2-main"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "pass2-main"
   }
  },
  "11": {
   "citation": {
    "verdict": "PASS",
    "stage": "pass2-main"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "pass2-main"
   }
  },
  "12": {
   "citation": {
    "verdict": "FAIL",
    "stage": "pass3-main",
    "chain": "closed-by-fix-record"
   },
   "qa": {
    "verdict": "FAIL",
    "stage": "pass2-main",
    "chain": "closed-by-fix-record"
   }
  },
  "13": {
   "citation": {
    "verdict": "PASS",
    "stage": "pass2-main"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "pass2-main"
   }
  },
  "14": {
   "citation": {
    "verdict": "PASS",
    "stage": "pass3-main"
   },
   "qa": {
    "verdict": "PASS",
    "stage": "pass2-main"
   }
  }
 },
 "events": [
  {
   "ts": "2026-07-25T11:39:14Z",
   "actor": "operator",
   "type": "milestone",
   "ref": "repo",
   "detail": "M1: kernel + registries + 23-test CI (2026-07-25)"
  },
  {
   "ts": "2026-07-25T11:39:14Z",
   "actor": "operator",
   "type": "milestone",
   "ref": "repo",
   "detail": "M2: memory layer - ranked retrieval, knowledge graph, context manager"
  },
  {
   "ts": "2026-07-25T11:39:14Z",
   "actor": "operator",
   "type": "verdict",
   "ref": "sections 2-7",
   "detail": "Pass 2 wave 1+2: 6/14 sections independently verified after ~70-finding fix cycles"
  },
  {
   "ts": "2026-07-25T11:39:14Z",
   "actor": "operator",
   "type": "decision",
   "ref": "DEC-014",
   "detail": "TLB-019 fee-mix label-shift proven and corrected at Facts layer"
  },
  {
   "ts": "2026-07-25T11:39:16Z",
   "actor": "aos-validate",
   "type": "validation",
   "ref": "repo",
   "detail": "verdict=FAIL"
  },
  {
   "ts": "2026-07-25T11:39:38Z",
   "actor": "aos-validate",
   "type": "validation",
   "ref": "repo",
   "detail": "verdict=PASS"
  },
  {
   "ts": "2026-07-25T15:54:29Z",
   "actor": "operator",
   "type": "milestone",
   "ref": "repo",
   "detail": "M3+M4: event bus, validate harness, workflow-first console with Inspector"
  },
  {
   "ts": "2026-07-25T16:16:23Z",
   "actor": "operator",
   "type": "milestone",
   "ref": "repo",
   "detail": "Two parallel verification lineages merged (PR #8 conflict resolved): union-of-corrections across 10 files, DEC-011 collision documented, 14/14 sections verified"
  }
 ],
 "metrics": {
  "total": 8,
  "by_type": {
   "milestone": 4,
   "verdict": 1,
   "decision": 1,
   "validation": 2
  },
  "by_actor": {
   "operator": 6,
   "aos-validate": 2
  }
 }
};
