"""Export kernel state to the console (the live-bridge contract, M4).

Writes app/agentic-os-console/src/js/kernel.js — a generated ES module the
workflow view renders. Regenerate whenever repo state moves:

    python3 scripts/aos/export_console.py

data.js remains the hand-curated snapshot for the descriptive views; kernel.js
is mechanical state (plan, verdicts, events) and is never hand-edited.
"""

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from scripts.aos import config, events, pipeline  # noqa: E402

OUT = ROOT / "app" / "agentic-os-console" / "src" / "js" / "kernel.js"


def validation_status():
    """Per-section citation/QA verdicts from Validation artifacts (best = reverify)."""
    out = {}
    vdir = ROOT / "vault" / "Validation"
    for n in range(1, 15):
        row = {}
        for kind, label in (("Citation_Audit", "citation"), ("QA_Review", "qa")):
            for suffix, tag in (("_v2_pass2_reverify", "reverify"), ("_v2_pass2", "pass2")):
                f = vdir / f"{kind}_Section_{n:02d}{suffix}.md"
                if f.exists():
                    m = re.search(r"^status:\s*(\S+)", f.read_text(encoding="utf-8", errors="replace")[:400], re.M)
                    row[label] = {"verdict": (m.group(1) if m else "?"), "stage": tag}
                    break
        out[n] = row
    return out


def workflow_stages(secs, stages, val):
    """Map repository state onto the 7-stage Goal→Publish rail."""
    verified = sum(1 for s in secs if s["status"] == "done_iv")
    part_a_done = sum(1 for s in stages["A"] if s["status"] == "done")
    gates_done = sum(1 for s in stages["C"] if s["status"] == "done")
    def st(done, active):
        return "done" if done else ("active" if active else "todo")
    return [
        {"id": "goal", "name": "Goal", "status": "done",
         "detail": "Problem Charter active — $175m allocation (pivoted 2026-07-23)"},
        {"id": "planning", "name": "Planning", "status": st(part_a_done == 12, part_a_done > 0),
         "detail": f"Part A setup {part_a_done}/12"},
        {"id": "execution", "name": "Execution", "status": st(verified == 14, True),
         "detail": f"{verified}/14 sections independently verified"},
        {"id": "validation", "name": "Validation", "status": st(gates_done == 6, verified == 14),
         "detail": f"Whole-plan gates {gates_done}/6"},
        {"id": "review", "name": "Review", "status": "todo", "detail": "Executive read-through after gates"},
        {"id": "approval", "name": "Approval", "status": "active",
         "detail": "Open: role mapping (6 members ↔ 5 roles); all 14 DEC records approved"},
        {"id": "publish", "name": "Publish", "status": "todo",
         "detail": "DOCX/PDF + OS doc + 30-slide deck → Outputs/"},
    ]


def main():
    secs = pipeline.sections()
    stages = pipeline.stages()
    plan = pipeline.plan()
    val = validation_status()
    kernel = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "goal": {"id": "GOAL-001", "name": "talabat 2026 $175m capital-allocation Business Plan",
                 "charter": "Problem_Charter.md"},
        "workflow": workflow_stages(secs, stages, val),
        "sections": secs,
        "plan": plan["next"],
        "waveBudget": config.MAX_CONCURRENT_AGENTS,
        "validation": val,
        "events": events.read(limit=60),
        "metrics": events.stats(),
    }
    OUT.write_text("/* GENERATED by scripts/aos/export_console.py — do not edit. */\n"
                   "export const KERNEL = " + json.dumps(kernel, ensure_ascii=False, indent=1) + ";\n")
    print(f"kernel.js written: {len(kernel['events'])} events, "
          f"{sum(1 for s in secs if s['status'] == 'done_iv')}/14 verified, "
          f"{len(plan['next'])} plan items")


if __name__ == "__main__":
    main()
